"""Build one-row-per-image binary pneumonia metadata from RSNA Stage 2 CSVs."""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


CLASS_INFO_NAME = "stage_2_detailed_class_info.csv"
LABELS_NAME = "stage_2_train_labels.csv"
TRAIN_IMAGE_DIR = Path("Data") / "stage_2_train_images"
TEST_IMAGE_DIR = Path("Data") / "stage_2_test_images"
METADATA_PATH = Path("metadata") / "pneumonia_metadata.csv"
STATS_PATH = Path("metadata") / "DATASET_STATS.md"
OUTPUT_COLUMNS = (
    "image_id",
    "image_path",
    "original_label",
    "binary_label",
    "x",
    "y",
    "width",
    "height",
    "bounding_box_available",
)
BOX_COLUMNS = ("x", "y", "width", "height")


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8-sig") as csv_file:
        reader = csv.DictReader(csv_file)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {path}")
        return list(reader)


def _normalize_label(label: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", label.casefold()).strip()


def _infer_label(
    labels: set[str], requested: str | None, role: str
) -> str:
    if requested is not None:
        if requested not in labels:
            raise ValueError(
                f"Requested {role} label {requested!r} was not found. "
                f"Available labels: {sorted(labels)}"
            )
        return requested

    if role == "pneumonia":
        candidates = {
            label
            for label in labels
            if ("pneumonia" in _normalize_label(label)
                or "lung opacity" in _normalize_label(label))
            and "no lung opacity" not in _normalize_label(label)
        }
    else:
        candidates = {
            label
            for label in labels
            if _normalize_label(label) in {"normal", "healthy"}
        }

    if len(candidates) != 1:
        raise ValueError(
            f"Could not uniquely infer the {role} class from labels "
            f"{sorted(labels)}. Pass --{role}-label with the exact CSV value."
        )
    return next(iter(candidates))


def _image_files(directory: Path) -> dict[str, Path]:
    if not directory.is_dir():
        raise FileNotFoundError(f"Image directory not found: {directory}")
    files: dict[str, Path] = {}
    for path in directory.iterdir():
        if path.is_file():
            key = path.stem.casefold()
            if key in files:
                raise ValueError(
                    f"Duplicate image ID {path.stem!r} in {directory}"
                )
            files[key] = path
    return files


def _numeric_coordinate(value: str, column: str, image_id: str) -> int | float:
    try:
        number = float(value)
    except ValueError as error:
        raise ValueError(
            f"Invalid {column} coordinate {value!r} for image {image_id}"
        ) from error
    if not math.isfinite(number):
        raise ValueError(f"Non-finite {column} coordinate for image {image_id}")
    if number.is_integer():
        return int(number)
    return number


def _write_stats(
    path: Path,
    *,
    disk_image_count: int,
    labeled_image_count: int,
    unlabeled_image_count: int,
    excluded_count: int,
    pneumonia_count: int,
    healthy_count: int,
    boxes_available: int,
    boxes_unavailable: int,
    multiple_box_images: int,
    pneumonia_label: str,
    healthy_label: str,
    excluded_labels: Counter[str],
) -> None:
    usable_count = pneumonia_count + healthy_count
    pneumonia_percent = 100 * pneumonia_count / usable_count
    healthy_percent = 100 * healthy_count / usable_count
    lines = [
        "# Dataset statistics",
        "",
        "Generated by `scripts/create_metadata.py` from the local RSNA Stage 2 "
        "training labels. Percentages are of the usable binary-classification "
        "cohort. Counts refer to unique image IDs, not CSV annotation rows.",
        "",
        "| Statistic | Count |",
        "|---|---:|",
        f"| Raw image files on disk (train + test folders) | {disk_image_count:,} |",
        f"| Labeled training images | {labeled_image_count:,} |",
        f"| Test images without labels in the supplied CSVs | {unlabeled_image_count:,} |",
        f"| Excluded labeled images (all other classes) | {excluded_count:,} |",
        f"| Usable images in metadata CSV | {usable_count:,} |",
        f"| Pneumonia (`{pneumonia_label}`) | {pneumonia_count:,} "
        f"({pneumonia_percent:.2f}%) |",
        f"| Healthy (`{healthy_label}`) | {healthy_count:,} "
        f"({healthy_percent:.2f}%) |",
        f"| Usable images with bounding boxes | {boxes_available:,} |",
        f"| Usable images without bounding boxes | {boxes_unavailable:,} |",
        f"| Images with multiple bounding boxes | {multiple_box_images:,} |",
        "",
        "## Excluded class counts",
        "",
        "| Original class | Unique images excluded |",
        "|---|---:|",
    ]
    lines.extend(
        f"| `{label}` | {count:,} |"
        for label, count in sorted(excluded_labels.items())
    )
    lines.extend(
        [
            "",
            "## Bounding-box representation",
            "",
            "There is one metadata row per image. For an image with one or more "
            "pneumonia boxes, each of `x`, `y`, `width`, and `height` is a JSON "
            "array stored in its CSV cell. Values at the same array index form "
            "one box, so multiple boxes are preserved without duplicating image "
            "rows or image files. Images without a box have `[]` in each "
            "coordinate cell and `bounding_box_available=false`; images with "
            "boxes have `bounding_box_available=true`.",
            "",
            "The actual class values were read from `stage_2_detailed_class_info.csv`. "
            f"The binary mapping is `{pneumonia_label}` → 1 and "
            f"`{healthy_label}` → 0. Other class values are excluded.",
            "",
            "## Reference-paper size check",
            "",
            "The reference description expects 17,489 usable images after "
            "excluding Diseased/No Pneumonia. This local Stage 2 labeled cohort "
            f"contains {usable_count:,} usable images "
            f"({usable_count - 17_489:+,} versus expected), so it does not "
            "match; the count was not adjusted to force a match. The local "
            f"usable total is {pneumonia_count:,} Pneumonia + "
            f"{healthy_count:,} Healthy, compared with the reference's 8,964 + "
            "8,525. The local labels contain "
            f"{excluded_count:,} excluded image IDs. The remaining "
            f"{unlabeled_image_count:,} on-disk files are in the test folder "
            "and have no labels in the supplied CSVs, so they cannot be assigned "
            "to the binary cohort. Dataset release/filtering differences explain "
            "why the available labeled cohort cannot reproduce the reported "
            "17,489 images from these files alone.",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def create_metadata(
    project_root: Path,
    *,
    pneumonia_label: str | None = None,
    healthy_label: str | None = None,
) -> dict[str, Any]:
    data_dir = project_root / "Data"
    class_rows = _read_csv(data_dir / CLASS_INFO_NAME)
    label_rows = _read_csv(data_dir / LABELS_NAME)

    class_by_id: dict[str, tuple[str, str]] = {}
    for row in class_rows:
        image_id = row["patientId"].strip()
        label = row["class"].strip()
        if not image_id or not label:
            raise ValueError("Class-info CSV contains an empty image ID or class")
        key = image_id.casefold()
        if key in class_by_id and class_by_id[key][1] != label:
            raise ValueError(f"Conflicting classes for image ID {image_id}")
        class_by_id[key] = (image_id, label)

    available_labels = {label for _, label in class_by_id.values()}
    if not available_labels:
        raise ValueError("No class labels found in class-info CSV")
    positive_label = _infer_label(available_labels, pneumonia_label, "pneumonia")
    negative_label = _infer_label(available_labels, healthy_label, "healthy")
    if positive_label == negative_label:
        raise ValueError("Pneumonia and healthy labels must be different")

    train_images = _image_files(project_root / TRAIN_IMAGE_DIR)
    test_images = _image_files(project_root / TEST_IMAGE_DIR)
    missing_images = sorted(set(class_by_id) - set(train_images))
    if missing_images:
        raise ValueError(
            f"{len(missing_images)} labeled IDs have no train image; "
            f"examples: {missing_images[:5]}"
        )

    boxes_by_id: dict[str, list[tuple[int | float, ...]]] = defaultdict(list)
    label_ids: set[str] = set()
    for row in label_rows:
        image_id = row["patientId"].strip()
        key = image_id.casefold()
        if not image_id:
            raise ValueError("Train-label CSV contains an empty image ID")
        label_ids.add(key)
        if key not in class_by_id:
            raise ValueError(f"Train-label ID {image_id} has no class-info row")
        target = row["Target"].strip()
        if target not in {"0", "1"}:
            raise ValueError(f"Unexpected Target={target!r} for image {image_id}")
        if target == "1":
            missing_coordinates = [
                column for column in BOX_COLUMNS if not row[column].strip()
            ]
            if missing_coordinates:
                raise ValueError(
                    f"Positive box row for {image_id} is missing "
                    f"coordinates: {missing_coordinates}"
                )
            box = tuple(
                _numeric_coordinate(row[column].strip(), column, image_id)
                for column in BOX_COLUMNS
            )
            boxes_by_id[key].append(box)

    if label_ids != set(class_by_id):
        missing_label_ids = sorted(set(class_by_id) - label_ids)
        raise ValueError(
            f"{len(missing_label_ids)} class-info IDs have no train-label row; "
            f"examples: {missing_label_ids[:5]}"
        )

    records: list[dict[str, str]] = []
    excluded_labels: Counter[str] = Counter()
    pneumonia_count = 0
    healthy_count = 0
    with_boxes_count = 0
    multiple_box_images = 0
    for key, (image_id, label) in sorted(
        class_by_id.items(), key=lambda item: item[1][0]
    ):
        image_boxes = boxes_by_id.get(key, [])
        if label == positive_label:
            if not image_boxes:
                raise ValueError(
                    f"Pneumonia image {image_id} has no positive box row"
                )
            binary_label = 1
            pneumonia_count += 1
            with_boxes_count += 1
            if len(image_boxes) > 1:
                multiple_box_images += 1
        elif label == negative_label:
            if image_boxes:
                raise ValueError(
                    f"Healthy image {image_id} unexpectedly has a positive box"
                )
            binary_label = 0
            healthy_count += 1
        else:
            if image_boxes:
                raise ValueError(
                    f"Excluded class image {image_id} has positive box rows"
                )
            excluded_labels[label] += 1
            continue

        coordinate_values = {
            column: json.dumps(
                [box[index] for box in image_boxes], separators=(",", ":")
            )
            for index, column in enumerate(BOX_COLUMNS)
        }
        image_path = train_images[key].relative_to(project_root).as_posix()
        records.append(
            {
                "image_id": image_id,
                "image_path": image_path,
                "original_label": label,
                "binary_label": str(binary_label),
                **coordinate_values,
                "bounding_box_available": (
                    "true" if image_boxes else "false"
                ),
            }
        )

    output_path = project_root / METADATA_PATH
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=OUTPUT_COLUMNS)
        writer.writeheader()
        writer.writerows(records)

    labeled_count = len(class_by_id)
    usable_count = len(records)
    _write_stats(
        project_root / STATS_PATH,
        disk_image_count=len(train_images) + len(test_images),
        labeled_image_count=labeled_count,
        unlabeled_image_count=len(test_images),
        excluded_count=sum(excluded_labels.values()),
        pneumonia_count=pneumonia_count,
        healthy_count=healthy_count,
        boxes_available=with_boxes_count,
        boxes_unavailable=usable_count - with_boxes_count,
        multiple_box_images=multiple_box_images,
        pneumonia_label=positive_label,
        healthy_label=negative_label,
        excluded_labels=excluded_labels,
    )

    return {
        "raw_image_files": len(train_images) + len(test_images),
        "labeled_images": labeled_count,
        "excluded_images": sum(excluded_labels.values()),
        "usable_images": usable_count,
        "pneumonia_images": pneumonia_count,
        "healthy_images": healthy_count,
        "images_with_boxes": with_boxes_count,
        "images_without_boxes": usable_count - with_boxes_count,
        "pneumonia_label": positive_label,
        "healthy_label": negative_label,
        "excluded_labels": dict(excluded_labels),
        "metadata_path": str(METADATA_PATH),
        "stats_path": str(STATS_PATH),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Create one metadata row per labeled Pneumonia or Normal image."
        )
    )
    parser.add_argument(
        "--pneumonia-label",
        help="Exact positive class value; inferred from CSV values if omitted.",
    )
    parser.add_argument(
        "--healthy-label",
        help="Exact negative class value; inferred from CSV values if omitted.",
    )
    args = parser.parse_args(argv)
    project_root = Path(__file__).resolve().parents[1]
    try:
        stats = create_metadata(
            project_root,
            pneumonia_label=args.pneumonia_label,
            healthy_label=args.healthy_label,
        )
    except (OSError, KeyError, ValueError, csv.Error) as error:
        print(f"Metadata generation failed: {error}", file=sys.stderr)
        return 1

    print("Metadata generation complete")
    for key, value in stats.items():
        print(f"{key}={value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
